name: Build DotNet package
on:
  push:
    tags:
      - v*

jobs:
  Deploy-Package:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup DotNet
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'
      - name: Install dependencies
        run: dotnet restore
        working-directory: ./SDI
      - name: Build
        run: dotnet build --configuration Release
        working-directory: ./SDI
      - name: Package project
        run: dotnet pack --configuration Release
        working-directory: ./SDI
      - name: Publish package
        run: dotnet nuget push bin/Release/*.nupkg --source https://api.nuget.org/v3/index.json -k ${{ secrets.NUGET_API_KEY }}
        working-directory: ./SDI
